### ISSUE TITLE
Sass and PostCSS

### ISSUE THREAD

**Issue by liliang-cn** [liliang-cn/logger#61]

**Comment by liliang-cn** [comment]
## CSS预处理器

在css的基础上提供了**精简代码**，**方便维护**的功能，最终文件会转译为常规的css文件，并不会提供新的特性（从浏览器的角度来看）

- Sass 
- Less
- PostCss

**Comment by liliang-cn** [comment]
## 嵌套的选择器

```sass
.site-nav {
  display: flex;

  > li {
    margin-top: 0;

    &.is-active {
      display: flex;
    }
  }
}
```

产出：
```css
.site-nav {
  display: flex;
}
.site-nav > li {
   margin-top: 0; 
}
.site-nav > li.is-active{
  display: flex; 
}
```
 _**嵌套会提高特指度，避免嵌套太深**_

**Comment by liliang-cn** [comment]
## 嵌套媒体查询

```sass
html {
  font-size: 1rem;

  @media (min-width: 45em) {
    font-size: 1.25rem;
  }
}
```

输出
```css
html {
  font-size: 1rem;
}

@media (min-width: 45em) {
  html {
    font-size: 1.25rem;
  }
}

```

**Comment by liliang-cn** [comment]
## Partials

```sass
@import 'partials/buttons';
```
`partials/buttons`:
```sass
.button {
  padding: 1em 1.25em;
  background-color: #265559;
  color: #333;
}
```
产出
```css
.button {
  padding: 1em 1.25em;
  background-color: #265559;
  color: #333;
}
```
